### ISSUE TITLE
google link to jar file dead

### ISSUE THREAD

**Issue by mpetruc** [clulab/pdf2txt#67]
First of all, thank you for time and effort developing this app, which seems really promising. Unfortunately the google link to the jar file seems to not work anymore:
"Sorry, the file you have requested does not exist.

Make sure that you have the correct URL and the file exists"

is there any other place where i can download it from?
thanks a lot.

**Comment by kwalcock** [comment]
Indeed.  The university changed providers and that drastically cut the amount of gdrive space we have, so I have to archive the file.  Unfortunately, I'm travelling and it will be about two days before I can retrieve it.  If you're daring, you could try to build it.  I think the jar is made with `sbt assembly`.  Thanks for being patient otherwise.

**Comment by kwalcock** [comment]
The file should be available at https://arizona.box.com/s/e13oc3mtyfb1v964bxle9xeneksavj04.  The link in the documentation will be updated momentarily.  Thanks for waiting!

**Comment by kwalcock** [comment]
@mpetruc, I hope this worked for you.
